### ISSUE TITLE
Retrieve collection of contacts from a ContactList

### ISSUE THREAD

**Issue by nibab** [constantcontact/ruby-sdk#26]
method is not implemented

**Comment by csciuto** [comment]
Covered in https://github.com/constantcontact/ruby-sdk/blob/master/lib/constantcontact/components/activities/add_contacts.rb now

**Comment by csciuto** [comment]
https://github.com/constantcontact/ruby-sdk/blob/master/lib/constantcontact/services/list_service.rb

get_contacts_from_list I believe returns this information.
