### ISSUE TITLE
What is 'Mashery'?

### ISSUE THREAD

**Issue by gregblass** [constantcontact/ruby-sdk#70]
The Readme on the home page makes reference to 'Mashery'?

I'm completely lost as to what that is.

**Comment by csciuto** [comment]
Hi Greg, Mashery is our API gateway. You need to get an API key through them. Please find the documents at https://developer.constantcontact.com/api-keys.html

Regards,

Corey

**Comment by gregblass** [comment]
Thank you! Was a little confusing coming here and not seeing that in the readme. (The readme should probably just quickly say what Mashery is for new users).
