### ISSUE TITLE
Version 4.1.0 does not exist on rubygems

### ISSUE THREAD

**Issue by eddiemonge** [constantcontact/ruby-sdk#72]
Docs say to add  `gem 'constantcontact', '~> 4.1.0'` but https://rubygems.org/gems/constantcontact only lists 4.0.0

**Comment by csciuto** [comment]
Ooof, by apologies. What happened here is that I cut the release for 4.0.0, revving the version for active development to 4.1.0, but the README should not have been updated. I'll correct that. Thanks for the report!
